export interface ReceiptData {
  number: string;
  date: string;
  amount: number | string;
  currency?: string;
  plan?: string;
  cycle?: string;
  method?: string;
  transactionId?: string;
  periodStart?: string;
  periodEnd?: string;
  customerEmail?: string;
  status?: string;
}

export function receiptHtml(d: ReceiptData): string {
  const cur = d.currency ?? "USD";
  const amt = typeof d.amount === "number" ? d.amount.toFixed(2) : d.amount;
  const row = (label: string, value?: string | number) =>
    value == null || value === "" ? "" : `<tr><td style="padding:6px 12px;color:#64748b;">${label}</td><td style="padding:6px 12px;text-align:right;color:#0f172a;font-weight:500;">${value}</td></tr>`;
  return `<!doctype html><html><head><meta charset="utf-8"/><title>Receipt ${d.number}</title>
<style>
 body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;background:#f8fafc;margin:0;padding:40px;color:#0f172a}
 .card{max-width:640px;margin:0 auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;overflow:hidden;box-shadow:0 10px 30px rgba(15,23,42,.06)}
 .hdr{padding:28px 32px;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff}
 .hdr h1{margin:0;font-size:22px;letter-spacing:.2px}
 .hdr p{margin:4px 0 0;opacity:.85;font-size:13px}
 .body{padding:24px 32px}
 .amount{font-size:36px;font-weight:700;margin:8px 0 4px}
 table{width:100%;border-collapse:collapse;margin-top:12px;font-size:14px;border-top:1px solid #e2e8f0}
 .foot{padding:16px 32px;background:#f1f5f9;font-size:12px;color:#64748b;text-align:center}
 .badge{display:inline-block;padding:2px 10px;border-radius:999px;background:#dcfce7;color:#166534;font-size:12px;font-weight:600}
 @media print{body{background:#fff;padding:0}.card{box-shadow:none;border:none}}
</style></head>
<body><div class="card">
 <div class="hdr">
  <h1>App2Rack — Payment Receipt</h1>
  <p>Receipt #${d.number}</p>
 </div>
 <div class="body">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;">
   <div>
    <div style="font-size:12px;color:#64748b;text-transform:uppercase;letter-spacing:.08em;">Amount paid</div>
    <div class="amount">${cur} ${amt}</div>
    <span class="badge">${d.status ?? "Paid"}</span>
   </div>
   <div style="text-align:right;font-size:13px;color:#64748b;">
    <div>${d.date}</div>
    ${d.customerEmail ? `<div style="margin-top:2px;">${d.customerEmail}</div>` : ""}
   </div>
  </div>
  <table>
   ${row("Plan", d.plan)}
   ${row("Billing cycle", d.cycle)}
   ${row("Payment method", d.method)}
   ${row("Transaction ID", d.transactionId)}
   ${row("Period start", d.periodStart)}
   ${row("Period end", d.periodEnd)}
  </table>
 </div>
 <div class="foot">Thank you for your business. This receipt was generated by App2Rack.</div>
</div>
<script>window.addEventListener("load",()=>{try{window.focus()}catch(e){}})</script>
</body></html>`;
}

export function downloadReceipt(d: ReceiptData) {
  const html = receiptHtml(d);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `receipt-${d.number}.html`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function printReceipt(d: ReceiptData) {
  const html = receiptHtml(d);
  const w = window.open("", "_blank", "width=720,height=900");
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
  setTimeout(() => { try { w.print(); } catch { /* ignore */ } }, 300);
}