/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServersRouteImport } from './routes/_authenticated/servers'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRacksRouteImport } from './routes/_authenticated/racks'
import { Route as AuthenticatedOptimizationAdvisorRouteImport } from './routes/_authenticated/optimization-advisor'
import { Route as AuthenticatedMappingRouteImport } from './routes/_authenticated/mapping'
import { Route as AuthenticatedLogAnalyzerRouteImport } from './routes/_authenticated/log-analyzer'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing.index'
import { Route as AuthenticatedCalculatorsStorageRouteImport } from './routes/_authenticated/calculators.storage'
import { Route as AuthenticatedCalculatorsRackRouteImport } from './routes/_authenticated/calculators.rack'
import { Route as AuthenticatedCalculatorsCloudRouteImport } from './routes/_authenticated/calculators.cloud'
import { Route as AuthenticatedBillingUsageRouteImport } from './routes/_authenticated/billing.usage'
import { Route as AuthenticatedBillingPricingRouteImport } from './routes/_authenticated/billing.pricing'
import { Route as AuthenticatedBillingCreditsRouteImport } from './routes/_authenticated/billing.credits'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServersRoute = AuthenticatedServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRacksRoute = AuthenticatedRacksRouteImport.update({
  id: '/racks',
  path: '/racks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOptimizationAdvisorRoute =
  AuthenticatedOptimizationAdvisorRouteImport.update({
    id: '/optimization-advisor',
    path: '/optimization-advisor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMappingRoute = AuthenticatedMappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogAnalyzerRoute =
  AuthenticatedLogAnalyzerRouteImport.update({
    id: '/log-analyzer',
    path: '/log-analyzer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalculatorsStorageRoute =
  AuthenticatedCalculatorsStorageRouteImport.update({
    id: '/calculators/storage',
    path: '/calculators/storage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalculatorsRackRoute =
  AuthenticatedCalculatorsRackRouteImport.update({
    id: '/calculators/rack',
    path: '/calculators/rack',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalculatorsCloudRoute =
  AuthenticatedCalculatorsCloudRouteImport.update({
    id: '/calculators/cloud',
    path: '/calculators/cloud',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingUsageRoute =
  AuthenticatedBillingUsageRouteImport.update({
    id: '/billing/usage',
    path: '/billing/usage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingPricingRoute =
  AuthenticatedBillingPricingRouteImport.update({
    id: '/billing/pricing',
    path: '/billing/pricing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingCreditsRoute =
  AuthenticatedBillingCreditsRouteImport.update({
    id: '/billing/credits',
    path: '/billing/credits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/log-analyzer': typeof AuthenticatedLogAnalyzerRoute
  '/mapping': typeof AuthenticatedMappingRoute
  '/optimization-advisor': typeof AuthenticatedOptimizationAdvisorRoute
  '/racks': typeof AuthenticatedRacksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/servers': typeof AuthenticatedServersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/billing/credits': typeof AuthenticatedBillingCreditsRoute
  '/billing/pricing': typeof AuthenticatedBillingPricingRoute
  '/billing/usage': typeof AuthenticatedBillingUsageRoute
  '/calculators/cloud': typeof AuthenticatedCalculatorsCloudRoute
  '/calculators/rack': typeof AuthenticatedCalculatorsRackRoute
  '/calculators/storage': typeof AuthenticatedCalculatorsStorageRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/log-analyzer': typeof AuthenticatedLogAnalyzerRoute
  '/mapping': typeof AuthenticatedMappingRoute
  '/optimization-advisor': typeof AuthenticatedOptimizationAdvisorRoute
  '/racks': typeof AuthenticatedRacksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/servers': typeof AuthenticatedServersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/billing/credits': typeof AuthenticatedBillingCreditsRoute
  '/billing/pricing': typeof AuthenticatedBillingPricingRoute
  '/billing/usage': typeof AuthenticatedBillingUsageRoute
  '/calculators/cloud': typeof AuthenticatedCalculatorsCloudRoute
  '/calculators/rack': typeof AuthenticatedCalculatorsRackRoute
  '/calculators/storage': typeof AuthenticatedCalculatorsStorageRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/log-analyzer': typeof AuthenticatedLogAnalyzerRoute
  '/_authenticated/mapping': typeof AuthenticatedMappingRoute
  '/_authenticated/optimization-advisor': typeof AuthenticatedOptimizationAdvisorRoute
  '/_authenticated/racks': typeof AuthenticatedRacksRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/servers': typeof AuthenticatedServersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/billing/credits': typeof AuthenticatedBillingCreditsRoute
  '/_authenticated/billing/pricing': typeof AuthenticatedBillingPricingRoute
  '/_authenticated/billing/usage': typeof AuthenticatedBillingUsageRoute
  '/_authenticated/calculators/cloud': typeof AuthenticatedCalculatorsCloudRoute
  '/_authenticated/calculators/rack': typeof AuthenticatedCalculatorsRackRoute
  '/_authenticated/calculators/storage': typeof AuthenticatedCalculatorsStorageRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/applications'
    | '/audit-logs'
    | '/dashboard'
    | '/import'
    | '/incidents'
    | '/log-analyzer'
    | '/mapping'
    | '/optimization-advisor'
    | '/racks'
    | '/reports'
    | '/servers'
    | '/settings'
    | '/billing/credits'
    | '/billing/pricing'
    | '/billing/usage'
    | '/calculators/cloud'
    | '/calculators/rack'
    | '/calculators/storage'
    | '/billing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/applications'
    | '/audit-logs'
    | '/dashboard'
    | '/import'
    | '/incidents'
    | '/log-analyzer'
    | '/mapping'
    | '/optimization-advisor'
    | '/racks'
    | '/reports'
    | '/servers'
    | '/settings'
    | '/billing/credits'
    | '/billing/pricing'
    | '/billing/usage'
    | '/calculators/cloud'
    | '/calculators/rack'
    | '/calculators/storage'
    | '/billing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/applications'
    | '/_authenticated/audit-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/incidents'
    | '/_authenticated/log-analyzer'
    | '/_authenticated/mapping'
    | '/_authenticated/optimization-advisor'
    | '/_authenticated/racks'
    | '/_authenticated/reports'
    | '/_authenticated/servers'
    | '/_authenticated/settings'
    | '/_authenticated/billing/credits'
    | '/_authenticated/billing/pricing'
    | '/_authenticated/billing/usage'
    | '/_authenticated/calculators/cloud'
    | '/_authenticated/calculators/rack'
    | '/_authenticated/calculators/storage'
    | '/_authenticated/billing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers': {
      id: '/_authenticated/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AuthenticatedServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/racks': {
      id: '/_authenticated/racks'
      path: '/racks'
      fullPath: '/racks'
      preLoaderRoute: typeof AuthenticatedRacksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/optimization-advisor': {
      id: '/_authenticated/optimization-advisor'
      path: '/optimization-advisor'
      fullPath: '/optimization-advisor'
      preLoaderRoute: typeof AuthenticatedOptimizationAdvisorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapping': {
      id: '/_authenticated/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof AuthenticatedMappingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log-analyzer': {
      id: '/_authenticated/log-analyzer'
      path: '/log-analyzer'
      fullPath: '/log-analyzer'
      preLoaderRoute: typeof AuthenticatedLogAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calculators/storage': {
      id: '/_authenticated/calculators/storage'
      path: '/calculators/storage'
      fullPath: '/calculators/storage'
      preLoaderRoute: typeof AuthenticatedCalculatorsStorageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calculators/rack': {
      id: '/_authenticated/calculators/rack'
      path: '/calculators/rack'
      fullPath: '/calculators/rack'
      preLoaderRoute: typeof AuthenticatedCalculatorsRackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calculators/cloud': {
      id: '/_authenticated/calculators/cloud'
      path: '/calculators/cloud'
      fullPath: '/calculators/cloud'
      preLoaderRoute: typeof AuthenticatedCalculatorsCloudRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/usage': {
      id: '/_authenticated/billing/usage'
      path: '/billing/usage'
      fullPath: '/billing/usage'
      preLoaderRoute: typeof AuthenticatedBillingUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/pricing': {
      id: '/_authenticated/billing/pricing'
      path: '/billing/pricing'
      fullPath: '/billing/pricing'
      preLoaderRoute: typeof AuthenticatedBillingPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/credits': {
      id: '/_authenticated/billing/credits'
      path: '/billing/credits'
      fullPath: '/billing/credits'
      preLoaderRoute: typeof AuthenticatedBillingCreditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedLogAnalyzerRoute: typeof AuthenticatedLogAnalyzerRoute
  AuthenticatedMappingRoute: typeof AuthenticatedMappingRoute
  AuthenticatedOptimizationAdvisorRoute: typeof AuthenticatedOptimizationAdvisorRoute
  AuthenticatedRacksRoute: typeof AuthenticatedRacksRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedServersRoute: typeof AuthenticatedServersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBillingCreditsRoute: typeof AuthenticatedBillingCreditsRoute
  AuthenticatedBillingPricingRoute: typeof AuthenticatedBillingPricingRoute
  AuthenticatedBillingUsageRoute: typeof AuthenticatedBillingUsageRoute
  AuthenticatedCalculatorsCloudRoute: typeof AuthenticatedCalculatorsCloudRoute
  AuthenticatedCalculatorsRackRoute: typeof AuthenticatedCalculatorsRackRoute
  AuthenticatedCalculatorsStorageRoute: typeof AuthenticatedCalculatorsStorageRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedLogAnalyzerRoute: AuthenticatedLogAnalyzerRoute,
  AuthenticatedMappingRoute: AuthenticatedMappingRoute,
  AuthenticatedOptimizationAdvisorRoute: AuthenticatedOptimizationAdvisorRoute,
  AuthenticatedRacksRoute: AuthenticatedRacksRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedServersRoute: AuthenticatedServersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBillingCreditsRoute: AuthenticatedBillingCreditsRoute,
  AuthenticatedBillingPricingRoute: AuthenticatedBillingPricingRoute,
  AuthenticatedBillingUsageRoute: AuthenticatedBillingUsageRoute,
  AuthenticatedCalculatorsCloudRoute: AuthenticatedCalculatorsCloudRoute,
  AuthenticatedCalculatorsRackRoute: AuthenticatedCalculatorsRackRoute,
  AuthenticatedCalculatorsStorageRoute: AuthenticatedCalculatorsStorageRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
